import { MantineColor } from "@mantine/core";
import type { Config } from "tailwindcss";
import defaultTheme from 'tailwindcss/defaultTheme';

type TailwindColorsTuples = {
  "0": string;
  "1": string;
  "2": string;
  "3": string;
  "4": string;
  "5": string;
  "6": string;
  "7": string;
  "8": string;
  "9": string;
  DEFAULT: string;
}
const defaultShade: number = 6;
/** @type {import('tailwindcss').Config} */
const mantineColor:Record<MantineColor, TailwindColorsTuples>  = {
  "primary": {
    "0": "var(--mantine-primary-color-0)",
    "1": "var(--mantine-primary-color-1)",
    "2": "var(--mantine-primary-color-2)",
    "3": "var(--mantine-primary-color-3)",
    "4": "var(--mantine-primary-color-4)",
    "5": "var(--mantine-primary-color-5)",
    "6": "var(--mantine-primary-color-6)",
    "7": "var(--mantine-primary-color-7)",
    "8": "var(--mantine-primary-color-8)",
    "9": "var(--mantine-primary-color-9)",
    "DEFAULT": `var(--mantine-primary-color-${defaultShade})`,
  },
  "secondary": {
    "0": "var(--mantine-color-secondary-0)",
    "1": "var(--mantine-color-secondary-1)",
    "2": "var(--mantine-color-secondary-2)",
    "3": "var(--mantine-color-secondary-3)",
    "4": "var(--mantine-color-secondary-4)",
    "5": "var(--mantine-color-secondary-5)",
    "6": "var(--mantine-color-secondary-6)",
    "7": "var(--mantine-color-secondary-7)",
    "8": "var(--mantine-color-secondary-8)",
    "9": "var(--mantine-color-secondary-9)",
    "DEFAULT": `var(--mantine-color-secondary-${defaultShade})`,
  },
  "danger": {
    "0": "var(--mantine-color-danger-0)",
    "1": "var(--mantine-color-danger-1)",
    "2": "var(--mantine-color-danger-2)",
    "3": "var(--mantine-color-danger-3)",
    "4": "var(--mantine-color-danger-4)",
    "5": "var(--mantine-color-danger-5)",
    "6": "var(--mantine-color-danger-6)",
    "7": "var(--mantine-color-danger-7)",
    "8": "var(--mantine-color-danger-8)",
    "9": "var(--mantine-color-danger-9)",
    "DEFAULT": `var(--mantine-color-danger-${defaultShade})`,
  },
  "success": {
    "0": "var(--mantine-color-success-0)",
    "1": "var(--mantine-color-success-1)",
    "2": "var(--mantine-color-success-2)",
    "3": "var(--mantine-color-success-3)",
    "4": "var(--mantine-color-success-4)",
    "5": "var(--mantine-color-success-5)",
    "6": "var(--mantine-color-success-6)",
    "7": "var(--mantine-color-success-7)",
    "8": "var(--mantine-color-success-8)",
    "9": "var(--mantine-color-success-9)",
    "DEFAULT": `var(--mantine-color-success-${defaultShade})`,
  },
  "warning": {
    "0": "var(--mantine-color-warning-0)",
    "1": "var(--mantine-color-warning-1)",
    "2": "var(--mantine-color-warning-2)",
    "3": "var(--mantine-color-warning-3)",
    "4": "var(--mantine-color-warning-4)",
    "5": "var(--mantine-color-warning-5)",
    "6": "var(--mantine-color-warning-6)",
    "7": "var(--mantine-color-warning-7)",
    "8": "var(--mantine-color-warning-8)",
    "9": "var(--mantine-color-warning-9)",
    "DEFAULT": `var(--mantine-color-warning-${defaultShade})`,
  },
  "info": {
    "0": "var(--mantine-color-info-0)",
    "1": "var(--mantine-color-info-1)",
    "2": "var(--mantine-color-info-2)",
    "3": "var(--mantine-color-info-3)",
    "4": "var(--mantine-color-info-4)",
    "5": "var(--mantine-color-info-5)",
    "6": "var(--mantine-color-info-6)",
    "7": "var(--mantine-color-info-7)",
    "8": "var(--mantine-color-info-8)",
    "9": "var(--mantine-color-info-9)",
    "DEFAULT": `var(--mantine-color-info-${defaultShade})`,
  },
  "tertiary": {
    "0": "var(--mantine-color-tertiary-0)",
    "1": "var(--mantine-color-tertiary-1)",
    "2": "var(--mantine-color-tertiary-2)",
    "3": "var(--mantine-color-tertiary-3)",
    "4": "var(--mantine-color-tertiary-4)",
    "5": "var(--mantine-color-tertiary-5)",
    "6": "var(--mantine-color-tertiary-6)",
    "7": "var(--mantine-color-tertiary-7)",
    "8": "var(--mantine-color-tertiary-8)",
    "9": "var(--mantine-color-tertiary-9)",
    "DEFAULT": `var(--mantine-color-tertiary-${defaultShade})`,
  },
  "dark": {
    "0": "var(--mantine-color-dark-0)",
    "1": "var(--mantine-color-dark-1)",
    "2": "var(--mantine-color-dark-2)",
    "3": "var(--mantine-color-dark-3)",
    "4": "var(--mantine-color-dark-4)",
    "5": "var(--mantine-color-dark-5)",
    "6": "var(--mantine-color-dark-6)",
    "7": "var(--mantine-color-dark-7)",
    "8": "var(--mantine-color-dark-8)",
    "9": "var(--mantine-color-dark-9)",
    "DEFAULT": `var(--mantine-color-dark-${defaultShade})`,
  },
  "gray": {
    "0": "var(--mantine-color-gray-0)",
    "1": "var(--mantine-color-gray-1)",
    "2": "var(--mantine-color-gray-2)",
    "3": "var(--mantine-color-gray-3)",
    "4": "var(--mantine-color-gray-4)",
    "5": "var(--mantine-color-gray-5)",
    "6": "var(--mantine-color-gray-6)",
    "7": "var(--mantine-color-gray-7)",
    "8": "var(--mantine-color-gray-8)",
    "9": "var(--mantine-color-gray-9)",
    "DEFAULT": `var(--mantine-color-gray-${defaultShade})`,
  },
  "red": {
    "0": "var(--mantine-color-red-0)",
    "1": "var(--mantine-color-red-1)",
    "2": "var(--mantine-color-red-2)",
    "3": "var(--mantine-color-red-3)",
    "4": "var(--mantine-color-red-4)",
    "5": "var(--mantine-color-red-5)",
    "6": "var(--mantine-color-red-6)",
    "7": "var(--mantine-color-red-7)",
    "8": "var(--mantine-color-red-8)",
    "9": "var(--mantine-color-red-9)",
    "DEFAULT": `var(--mantine-color-red-${defaultShade})`,
  },
  "pink": {
    "0": "var(--mantine-color-pink-0)",
    "1": "var(--mantine-color-pink-1)",
    "2": "var(--mantine-color-pink-2)",
    "3": "var(--mantine-color-pink-3)",
    "4": "var(--mantine-color-pink-4)",
    "5": "var(--mantine-color-pink-5)",
    "6": "var(--mantine-color-pink-6)",
    "7": "var(--mantine-color-pink-7)",
    "8": "var(--mantine-color-pink-8)",
    "9": "var(--mantine-color-pink-9)",
    "DEFAULT": `var(--mantine-color-pink-${defaultShade})`,
  },
  "grape": {
    "0": "var(--mantine-color-grape-0)",
    "1": "var(--mantine-color-grape-1)",
    "2": "var(--mantine-color-grape-2)",
    "3": "var(--mantine-color-grape-3)",
    "4": "var(--mantine-color-grape-4)",
    "5": "var(--mantine-color-grape-5)",
    "6": "var(--mantine-color-grape-6)",
    "7": "var(--mantine-color-grape-7)",
    "8": "var(--mantine-color-grape-8)",
    "9": "var(--mantine-color-grape-9)",
    "DEFAULT": `var(--mantine-color-grape-${defaultShade})`,
  },
  "violet": {
    "0": "var(--mantine-color-violet-0)",
    "1": "var(--mantine-color-violet-1)",
    "2": "var(--mantine-color-violet-2)",
    "3": "var(--mantine-color-violet-3)",
    "4": "var(--mantine-color-violet-4)",
    "5": "var(--mantine-color-violet-5)",
    "6": "var(--mantine-color-violet-6)",
    "7": "var(--mantine-color-violet-7)",
    "8": "var(--mantine-color-violet-8)",
    "9": "var(--mantine-color-violet-9)",
    "DEFAULT": `var(--mantine-color-violet-${defaultShade})`,
  },
  "indigo": {
    "0": "var(--mantine-color-indigo-0)",
    "1": "var(--mantine-color-violet-1)",
    "2": "var(--mantine-color-violet-2)",
    "3": "var(--mantine-color-violet-3)",
    "4": "var(--mantine-color-violet-4)",
    "5": "var(--mantine-color-violet-5)",
    "6": "var(--mantine-color-violet-6)",
    "7": "var(--mantine-color-violet-7)",
    "8": "var(--mantine-color-violet-8)",
    "9": "var(--mantine-color-violet-9)",
    "DEFAULT": `var(--mantine-color-violet-${defaultShade})`,
  },
  "blue": {
    "0": "var(--mantine-color-blue-0)",
    "1": "var(--mantine-color-blue-1)",
    "2": "var(--mantine-color-blue-2)",
    "3": "var(--mantine-color-blue-3)",
    "4": "var(--mantine-color-blue-4)",
    "5": "var(--mantine-color-blue-5)",
    "6": "var(--mantine-color-blue-6)",
    "7": "var(--mantine-color-blue-7)",
    "8": "var(--mantine-color-blue-8)",
    "9": "var(--mantine-color-blue-9)",
    "DEFAULT": `var(--mantine-color-blue-${defaultShade})`,
  },
  "cyan": {
    "0": "var(--mantine-color-cyan-0)",
    "1": "var(--mantine-color-cyan-1)",
    "2": "var(--mantine-color-cyan-2)",
    "3": "var(--mantine-color-cyan-3)",
    "4": "var(--mantine-color-cyan-4)",
    "5": "var(--mantine-color-cyan-5)",
    "6": "var(--mantine-color-cyan-6)",
    "7": "var(--mantine-color-cyan-7)",
    "8": "var(--mantine-color-cyan-8)",
    "9": "var(--mantine-color-cyan-9)",
    "DEFAULT": `var(--mantine-color-cyan-${defaultShade})`,
  },
  "teal": {
    "0": "var(--mantine-color-teal-0)",
    "1": "var(--mantine-color-teal-1)",
    "2": "var(--mantine-color-teal-2)",
    "3": "var(--mantine-color-teal-3)",
    "4": "var(--mantine-color-teal-4)",
    "5": "var(--mantine-color-teal-5)",
    "6": "var(--mantine-color-teal-6)",
    "7": "var(--mantine-color-teal-7)",
    "8": "var(--mantine-color-teal-8)",
    "9": "var(--mantine-color-teal-9)",
    "DEFAULT": `var(--mantine-color-teal-${defaultShade})`,
  },
  "green": {
    "0": "var(--mantine-color-green-0)",
    "1": "var(--mantine-color-green-1)",
    "2": "var(--mantine-color-green-2)",
    "3": "var(--mantine-color-green-3)",
    "4": "var(--mantine-color-green-4)",
    "5": "var(--mantine-color-green-5)",
    "6": "var(--mantine-color-green-6)",
    "7": "var(--mantine-color-green-7)",
    "8": "var(--mantine-color-green-8)",
    "9": "var(--mantine-color-green-9)",
    "DEFAULT": `var(--mantine-color-green-${defaultShade})`,
  },
  "lime": {
    "0": "var(--mantine-color-lime-0)",
    "1": "var(--mantine-color-lime-1)",
    "2": "var(--mantine-color-lime-2)",
    "3": "var(--mantine-color-lime-3)",
    "4": "var(--mantine-color-lime-4)",
    "5": "var(--mantine-color-lime-5)",
    "6": "var(--mantine-color-lime-6)",
    "7": "var(--mantine-color-lime-7)",
    "8": "var(--mantine-color-lime-8)",
    "9": "var(--mantine-color-lime-9)",
    "DEFAULT": `var(--mantine-color-lime-${defaultShade})`,
  },
  "yellow": {
    "0": "var(--mantine-color-yellow-0)",
    "1": "var(--mantine-color-yellow-1)",
    "2": "var(--mantine-color-yellow-2)",
    "3": "var(--mantine-color-yellow-3)",
    "4": "var(--mantine-color-yellow-4)",
    "5": "var(--mantine-color-yellow-5)",
    "6": "var(--mantine-color-yellow-6)",
    "7": "var(--mantine-color-yellow-7)",
    "8": "var(--mantine-color-yellow-8)",
    "9": "var(--mantine-color-yellow-9)",
    "DEFAULT": `var(--mantine-color-yellow-${defaultShade})`,
  },
  "orange": {
    "0": "var(--mantine-color-orange-0)",
    "1": "var(--mantine-color-orange-1)",
    "2": "var(--mantine-color-orange-2)",
    "3": "var(--mantine-color-orange-3)",
    "4": "var(--mantine-color-orange-4)",
    "5": "var(--mantine-color-orange-5)",
    "6": "var(--mantine-color-orange-6)",
    "7": "var(--mantine-color-orange-7)",
    "8": "var(--mantine-color-orange-8)",
    "9": "var(--mantine-color-orange-9)",
    "DEFAULT": `var(--mantine-color-orange-${defaultShade})`,
  }
}

const config: Config = {
  corePlugins: {
    preflight: false,
  },
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        black: "#1f1f1f",
        ...mantineColor,
      },
      screens: {
        "2xsm": "375px",
        xsm: "425px",
        "3xl": "2000px",
      },
      fontSize: {
        xxs: '.625rem',
        xs: '.75rem',
        sm: '.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '4rem',
        '7xl': '5rem'
      },
      fontFamily: {
        sans: ["Open Sans", 'sans-serif', ...defaultTheme.fontFamily.sans],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;