version: '3.7'

services:
  airso-folder-api:
    container_name: airso-folder-api
    # user: 'myuser'
    # depends_on:
    #   - airso-image-db
    build:
      context: ../../
      args:
        - APP=folder-service
      target: production
    command: >
      sh -c "npm run migration:run-prod --app_name=folder-service && node dist/main"
    # command: npm run start -- folder-service
    # command: >
    #   sh -c "npm run migration:run-dev && npm run start"
    ports:
      - 3002:3000
    env_file:
      - ../../apps/folder-service/.env.development
    networks:
      - ${GLOBAL_NETWORK:-services}
  airso-folder-db:
    container_name: airso-folder-db
    image: postgres
    ports:
      - 5432:5432
    labels:
      - 'traefik.enable=true'
      - 'traefik.tcp.routers.airso-folder-db.rule=HostSNI(`dev.db.folder.airso.digibay.id`)'
      - 'traefik.tcp.routers.airso-folder-db.entrypoints=postgresql'
      - 'traefik.tcp.routers.airso-folder-db.service=airso-folder-db'
      - 'traefik.tcp.routers.airso-folder-db.tls=true'
      - 'traefik.tcp.routers.airso-folder-db.tls.certresolver=production'
      - 'traefik.tcp.services.airso-folder-db.loadbalancer.server.port=5432'
      - 'traefik.docker.network=traefik'
    environment:
      POSTGRES_USER: airso
      POSTGRES_PASSWORD: pass123
    volumes:
      - airso_folder_db:/var/lib/postgresql/data
    networks:
      # - traefik
      - ${GLOBAL_NETWORK:-services}
  # airso-file-api:
  #   container_name: airso-file-api
  #   # depends_on:
  #   #   - airso-image-db
  #   build:
  #     context: ../../
  #     args:
  #       - APP=file-service
  #     target: production
  #   # command: npm run start -- file-service
  #   # command: >
  #   #   sh -c "npm run migration:run-dev && npm run start"
  #   ports:
  #     - 3003:3000
  #   env_file:
  #     - ../../apps/file-service/.env.development
  #   networks:
  #     - ${GLOBAL_NETWORK:-services}
  nats:
    image: nats:latest
    ports:
      - '4222:4222'
      - '8222:8222'
    command:
      - '-user'
      - 'digibay'
      - '-pass'
      - 'pass123'
    networks:
      - ${GLOBAL_NETWORK:-services}

volumes:
  airso_folder_db:
    name: airso_folder_db
